services:
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./:/local
    command: generate -g typescript-axios -i local/openapi/openapi.yml -o local/frontend/src/generated
