services:
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./:/local
    command: generate -g typescript-fetch --additional-properties=aspnetCoreVersion=3.1 -i local/openapi/openapi.yml -o local/frontend/src/generated
