openapi: 3.0.0
info:
  title: Simple User API
  description: A simple API to retrieve user information.
  version: 1.0.0
paths:
  /hello:
    get:
      description: Returns a simple hello message.
      responses:
        '200':
          description: Hello message returned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  lang:
                    type: string
                  message:
                    type: string
              examples:
                default:
                  value:
                    lang: ja
                    message: こんにちは 世界
      operationId: getHello
  /posts:
    get:
      description: Retrieve all posts.
      responses:
        '200':
          description: Posts retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllPostsResponse'
              examples:
                default:
                  value:
                    - id: 1
                      title: 'Hello, World!'
                      body: This is my first post.
                      userName: John Doe
                      createdAt: '2021-01-01T00:00:00Z'
                      updatedAt: '2021-01-01T00:00:00Z'
                    - id: 2
                      title: 'Hello, World! (2)'
                      body: This is my second post.
                      userName: John Doe
                      createdAt: '2021-01-02T00:00:00Z'
                      updatedAt: '2021-01-02T00:00:00Z'
      operationId: getAllPosts
      tags:
        - post
      summary: ''
  '/posts/{postId}':
    get:
      description: Retrieve post information by ID.
      parameters:
        - name: postId
          in: path
          description: The unique identifier of the post.
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Post information retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
              examples:
                default:
                  value:
                    id: 1
                    title: 'Hello, World!'
                    body: This is my first post.
                    userName: John Doe
                    createdAt: '2021-01-01T00:00:00Z'
                    updatedAt: '2021-01-01T00:00:00Z'
        '404':
          description: Post not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      operationId: getPostById
      summary: ''
      tags:
        - post
tags:
  - name: post
    description: Tag for post
components:
  schemas:
    Post:
      title: Post
      x-stoplight:
        id: hj9bme3vgahy1
      type: object
      properties:
        id:
          type: number
          x-stoplight:
            id: c9g5l8ge8l3ge
        title:
          type: string
          x-stoplight:
            id: vg92e13m8yxcc
        body:
          type: string
          x-stoplight:
            id: 05k7m4ngjsfno
        userName:
          type: string
          x-stoplight:
            id: 7rhepi8aiwyw6
        createdAt:
          type: string
          x-stoplight:
            id: m6p2rziqtbhqe
        updatedAt:
          type: string
          x-stoplight:
            id: 6v7jk8gkrrd4y
    User:
      title: User
      x-stoplight:
        id: drgvswrqymdqc
      type: object
      properties:
        id:
          type: integer
          x-stoplight:
            id: nu795mv9xfj6q
        name:
          type: string
          x-stoplight:
            id: 5y8q2ug02vgas
        password:
          type: string
          x-stoplight:
            id: 1nmbr7ntg0gby
        createdAt:
          type: string
          x-stoplight:
            id: wce1sclnefiey
          format: date-time
        updatedAt:
          type: string
          x-stoplight:
            id: wcwxnu83ad5f6
          format: date-time
    GetPostResponse:
      $ref: '#/components/schemas/Post'
    GetAllPostsResponse:
      title: GetAllPostsResponse
      x-stoplight:
        id: so8ngu35yoxlo
      type: array
      items:
        $ref: '#/components/schemas/Post'
  responses: {}
servers:
  - url: 'http://localhost:9000'
    description: local server
