openapi: 3.0.0
info:
  title: Simple User API
  description: A simple API to retrieve user information.
  version: 1.0.0

paths:
  /hello:
    get:
      description: Returns a simple hello message.
      responses:
        "200":
          description: Hello message returned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  lang:
                    type: string
                  message:
                    type: string
              examples:
                default:
                  value:
                    lang: ja
                    message: こんにちは 世界         
  /posts:
    get:
      description: Retrieve all posts.
      responses:
        "200":
          description: Posts retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    title:
                      type: string
                    body:
                      type: string
                    userName:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
                    updatedAt:
                      type: string
                      format: date-time
              examples:
                default:
                  value:
                    - id: 1
                      title: "Hello, World!"
                      body: "This is my first post."
                      userName: "John Doe"
                      createdAt: "2021-01-01T00:00:00Z"
                      updatedAt: "2021-01-01T00:00:00Z"
                    - id: 2
                      title: "Hello, World! (2)"
                      body: "This is my second post."
                      userName: "John Doe"
                      createdAt: "2021-01-02T00:00:00Z"
                      updatedAt: "2021-01-02T00:00:00Z"
    post:
      description: Create a new post.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                user_name:
                  type: string
              required:
                - title
                - body
                - userName
              example:
                title: "Hello, World!"
                body: "This is my first post."
                user_name: "John Doe"
      responses:
        "201":
          description: Post created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  title:
                    type: string
                  body:
                    type: string
                  user_name:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
              examples:
                default:
                  value:
                    id: 1
                    title: "Hello, World!"
                    body: "This is my first post."
                    user_name: "John Doe"
                    createdAt: "2021-01-01T00:00:00Z"
                    updatedAt: "2021-01-01T00:00:00Z"

  /posts/{postId}:
    get:
      description: Retrieve post information by ID.
      parameters:
        - name: postId
          in: path
          description: The unique identifier of the post.
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: Post information retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  title:
                    type: string
                  body:
                    type: string
                  userName:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
              examples:
                default:
                  value:
                    id: 1
                    title: "Hello, World!"
                    body: "This is my first post."
                    userName: "John Doe"
                    createdAt: "2021-01-01T00:00:00Z"
                    updatedAt: "2021-01-01T00:00:00Z"
        "404":
          description: Post not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
