openapi: 3.0.0
info:
  title: Simple User API
  description: A simple API to retrieve user information.
  version: 1.0.0
paths:
  /hello:
    get:
      description: Returns a simple hello message.
      responses:
        '200':
          description: Hello message returned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  lang:
                    type: string
                  message:
                    type: string
              examples:
                default:
                  value:
                    lang: ja
                    message: こんにちは 世界
      operationId: getHello
  /posts:
    get:
      description: Retrieve all posts.
      responses:
        '200':
          description: Posts retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllPostsResponse'
              examples:
                default:
                  value:
                    - id: 1
                      title: 'Hello, World!'
                      body: This is my first post.
                      userName: John Doe
                      createdAt: '2021-01-01T00:00:00Z'
                      updatedAt: '2021-01-01T00:00:00Z'
                    - id: 2
                      title: 'Hello, World! (2)'
                      body: This is my second post.
                      userName: John Doe
                      createdAt: '2021-01-02T00:00:00Z'
                      updatedAt: '2021-01-02T00:00:00Z'
      operationId: getAllPosts
      tags:
        - post
      summary: ''
    post:
      description: Create a new post.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePostRequest'
            examples:
              default:
                value:
                  title: "Hello, World!"
                  body: "This is my first post."
                  user_id: 0
      responses:
        "201":
          description: Post created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePostResponse'
              examples:
                default:
                  value:
                    id: 1
                    title: "Hello, World!"
                    body: "This is my first post."
                    user_id: 0
                    createdAt: "2021-01-01T00:00:00Z"
                    updatedAt: "2021-01-01T00:00:00Z"
      operationId: postPost
      tags:
        - post
      summary: ''
    
  '/posts/{postId}':
    get:
      description: Retrieve post information by ID.
      parameters:
        - name: postId
          in: path
          description: The unique identifier of the post.
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Post information retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
              examples:
                default:
                  value:
                    id: 1
                    title: 'Hello, World! updated'
                    body: This is my updated post.
                    userName: John Doe
                    createdAt: '2021-01-01T00:00:00Z'
                    updatedAt: '2021-01-01T00:00:00Z'
        '404':
          description: Post not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      operationId: getPostById
      summary: ''
      tags:
        - post
    put:
      description: Update a post by ID.
      parameters:
        - name: postId
          in: path
          description: The unique identifier of the post.
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePostRequest'
            examples:
              default:
                value:
                  title: "Hello, World!"
                  body: "This is my first post."
      responses:
        "200":
          description: Post updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdatePostResponse'
              examples:
                default:
                  value:
                    id: 1
                    title: "Hello, World!"
                    body: "This is my first post."
                    user_id: 0
                    createdAt: "2021-01-01T00:00:00Z"
                    updatedAt: "2021-01-01T00:00:00Z"
        "404":
          description: Post not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      operationId: putPost
      tags:
        - post
      summary: ''
    delete:
      description: Delete a post.
      operationId: deletePost
      parameters:
        - name: postId
          in: path
          description: The unique identifier of the post.
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: Post deleted successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletePostResponse'
              examples:
                default:
                  value:
                    succeeded: true
        "400":
          description: Failed to delete a post.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      tags:
        - post
tags:
  - name: post
    description: Tag for post
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        password:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Post:
      title: Post
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        body:
          type: string
        userName:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
      required:
        - id
        - title
        - body
        - userName
        - createdAt
        - updatedAt
    CreatePostRequest:
      title: CreatePostRequest
      type: object
      properties:
        title:
          type: string
        body:
          type: string
        user_id:
          type: integer
      required:
        - title
        - body
        - user_id
    CreatePostResponse:
      title: CreatePostResponse
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        body:
          type: string
        user_id:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    UpdatePostRequest:
      title: UpdatePostRequest
      type: object
      properties:
        title:
          type: string
        body:
          type: string
      required:
        - title
        - body
    UpdatePostResponse:
      title: UpdatePostResponse
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        body:
          type: string
        user_id:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - title
        - body
        - user_id
        - createdAt
        - updatedAt
    GetPostResponse:
      $ref: '#/components/schemas/Post'
    GetAllPostsResponse:
      title: GetAllPostsResponse
      type: array
      items:
        $ref: '#/components/schemas/Post'
    DeletePostResponse:
      title: DeletePostResponse
      type: object
      properties:
        succeeded:
          type: boolean
  responses: {}
servers:
  - url: 'http://localhost:9000'
    description: local server
