name: Check build for backend

on:
  pull_request:
    paths:
      - "backend/**"

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'
    - name: Build
      working-directory: ./backend
      run: go build -o myapp
